# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- secretvars

pool:
  vmImage: ubuntu-latest

variables:
- group: vgdemo

steps:
- script: echo $(StorageAccountName)
- script: echo $(subscriptionID)
- script: echo $(vgdemovar1)
- script: echo $(vgdemovar2)
#- task: AzureResourceManagerTemplateDeployment@3
#  inputs:
#    deploymentScope: 'Resource Group'
#    #give this mapped to valid subscriptionID
#    azureResourceManagerConnection: 'azure-cpg-test' 
#    action: 'Create Or Update Resource Group'
#    resourceGroupName: $(resourceGroupName)
#    location: $(location)
#    templateLocation: 'URL of the file'
#    csmFileLink: 'https://raw.githubusercontent.com/k-bhavitha/arm-template-trials/secretvars/CreateWebApp/secretvars.json'
#    deploymentMode: 'Incremental'
#    deploymentName: 'DevopsVM'
#    overrideParameters: '-StorageAccountName $(StorageAccountName)'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

